# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build, javadoc, and test with Gradle
      run: ./gradlew javadoc test
    - name: Archive javadoc results
      uses: actions/upload-artifact@v1
      with:
        name: javadoc-report
        path: build/docs/javadoc
    - name: Archive junit results
      uses: actions/upload-artifact@v1
      with:
        name: junit-report
        path: build/reports/tests/test/
